# -*- coding: utf-8 -*-
"""lab_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19dAaZ-5LvbPNsn18QSlmbbckUKx_W6v-
"""

#lab_2A

import matplotlib.pyplot as plt
sub=['Physics','Maths','C Language','electronics','english']
marks=[91,98,87,96,85]
plt.plot(sub,marks)
plt.xlabel('subjects')
plt.ylabel('marks')
plt.title('1NT22CS002:Aashutosh')
plt.show()

#lab_2B

import matplotlib.pyplot as plt
sub = ['Physics', 'Maths', 'C Language', 'Electronics', 'English']
marks = [91, 98, 87, 96, 86]
plt.plot(sub, marks, marker='o', color='b', linestyle='-', linewidth=2)
plt.xlabel('Subjects')
plt.ylabel('Marks')
plt.title('1NT22CS002:Aashutosh')
plt.show()