# -*- coding: utf-8 -*-
"""lab_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODcCD7wF9G3MZmjD2NFsLT4B_fkFFCEf
"""

import pandas as pd
import plotly.express as px
election=pd.read_csv("election.csv")
election=election[0:500]
fig=px.scatter(election,x="STATE",y="NAME",marginal_x="histogram",marginal_y="rug",color="GENDER",title="Election Data")
fig.show()

